---

name: 'Update of assets'

on:
  workflow_dispatch:
  schedule:
    # Run every week on Sunday at 00:00 AM UTC
    - cron: '0 0 * * 0'

jobs:
  build:
    name: 'Build assets'
    runs-on: [ubuntu-latest]

    steps:
      - name: 'Run assets build (2.1)'
        uses: actions/github-script@v7
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'build-release.yml',
              ref: 'release-2.1'
            })

      - name: 'Run assets build (2.2)'
        uses: actions/github-script@v7
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'build-release.yml',
              ref: 'release-2.2'
            })

      - name: 'Run assets build (2.3)'
        uses: actions/github-script@v7
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'build-release.yml',
              ref: 'release-2.3'
            })
