---

name: 'Update dependencies'

on:
  workflow_dispatch:
  schedule:
    # Run every week on Sunday at 00:00 AM UTC
    - cron: '15 0 * * 0'

jobs:
  build:
    name: 'Update dependencies'
    runs-on: [ubuntu-latest]

    steps:
      - name: 'Run developer-tools update (2.3)'
        uses: actions/github-script@v8
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'update-dependencies.yml',
              ref: 'release-2.3'
            })

      - name: 'Run developer-tools update (2.4)'
        uses: actions/github-script@v8
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'update-dependencies.yml',
              ref: 'release-2.4'
            })

      - name: 'Run developer-tools update (2.5)'
        uses: actions/github-script@v8
        with:
          # Token has to be generated on a user account that controls the remote repository.
          # The _only_ scope to select is "Access public repositories", nothing more.
          github-token: "${{ secrets.PAT_TOKEN }}"
          debug: true
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'simplesamlphp',
              repo: 'simplesamlphp-assets-jquery',
              workflow_id: 'update-dependencies.yml',
              ref: 'release-2.5'
            })
